elementary/os

.github/workflows/daily.yml
I've pushed my alternative build scripts (that use unadulterated Debian live-build, instead of Ubuntu live-build) for the .iso to the `debian-live-build` branch for now. This adds the necessary bits to our workflow file to build and upload an .iso image nightly using that method.
If I've done everything right, they should be uploaded to the same place as the current ones and called `elementaryos-5.1-daily.YYYYMMDD-deb-live-build.iso`.
I'm working on the README in that branch to document everything I've discovered and the methodology. If we decide we want to use this method, we can move that info to the wiki I guess and then move some stuff across into `master`.
=> Add alternative build

.github/workflows/daily-alternative.yml
Made a bit of a mistake with the path here. We create an `artifacts` folder in the current directory and then try and mount `/artifacts` in the container. Make sure we prefix it with the working directory.
=> Fix artifacts path

build.sh
The first stage of the `live-build` process is to bootstrap a very minimal Ubuntu environment to chroot into before installing packages inside there and building the image.
Once in the chroot, Ubuntu packages can be verified as the base system comes with the Ubuntu keyring. But the initial stage of building the chroot couldn't due to the Debian host. Turns out Debian have the Ubuntu keys in their repo, so that's useful and removes some warnings during the build.
=> Install ubuntu-keyring in Debian host

etc/config/package-lists.distinst/desktop.list.chroot_live
This results in an installable distinst .iso (which we don't currently build in CI yet) with a fully working initial setup and onboarding flow. The live session on the .iso doesn't work properly yet (with or without this PR), but this is definitely closer to the end goal than the current config.
=> Simplify distinst live package lists

build.sh
__CHANGES:__
* Link the focal debootstrap script to the gutsy script until debootstrap 1.0.117 or newer is available.
Resolves https://github.com/elementary/os/issues/277
=> symlink focal script

build.sh
__CHANGES:__
* Fix the path to the appcenter files for builds that want to include the appcenter ppa.
=> use copy with the correct paths to fix builds that include appcenter

etc/auto/config, etc/terraform.conf
This should select better sources when setting up /etc/apt/sources.list
=> use ubuntu mirrors instead of archive.ubuntu.com

etc/auto/config
Looks like the GitHub actions CI environment has been running out of space during the build recently and failing the job as a result. These are some options to not save downloaded packages and build stages to the disk in the hope it leaves us with more free space.
These options are useless in single use CI environments anyway as the cache is gone on the next build.
=> Disable caching

.github/workflows/daily-5.1.yml, .github/workflows/daily-6.0-pinebookpro.yml, .github/workflows/daily-6.0.yml, .github/workflows/distinst-weekly.yml, .github/workflows/stable.yml
- formatting
- pinebook build on push master
- manually trigger builds
=> Update github actions

upload.sh
When I looked through the scripts, I noticed there's an extra space character in a comment in the upload.sh script.
It's a small detail, but it's always something that bothers me once I've spotted it.
=> remove double space in upload.sh

etc/config/hooks/live/001-install-flatpaks.chroot
This has the caveats mentioned on the call:
- flathub gets included so needs filtering
- will probably be adwaita
- will need to figure how to set it as default browser
Additionally, this will only work for the amd64 iso for now. I need to rework the pinebook build scripts slightly to ensure the same hooks get run for both.
=> Install epiphany as systemwide flatpak

build.sh
Workaround for #396. Would I need to do the same for `md5sum`?
=> Only include filename in sha256 output

.github/workflows/daily-6.0-pinebookpro.yml, build-pinebookpro.sh
Instead of duplicating code to remove unwanted packages and cleanup, run the same scripts from the `hooks` directory that do this and install Flatpak Epiphany.
This will bring the pinebookpro images to the same feature parity as the amd64 ones regarding Flatpak Epiphany.
I have tested that this produces working images.
=> pinebookpro: Run same hooks as amd64 iso

etc/auto/config, etc/terraform-daily-5.1-azure.conf, etc/terraform-daily-5.1-distinst-azure.conf, etc/terraform-daily-6.0-azure.conf, etc/terraform-stable-azure.conf, etc/terraform.conf
Fixes #445 
The previous scripts assumed that if we were building a HWE image, there would also be a HWE version of XOrg. This doesn't seem to be true for focal (yet?), so we need to separate out the two config options.
This also enables installation of the HWE kernel for Odin. I've tested an iso built with these changes, and verified that it boots successfully with the 5.8 kernel.
=> Separate HWE packages and enable for odin

build-rpi.sh
Fixes #457 
We were missing a package, and there's a bug in 20.04 (which doesn't officially support the Pi 400) that means we have to symlink the firmware directory so that the Bluetooth driver looks in the right place for it instead of in `/etc/firmware` which doesn't exist.
=> rpi: Bluetooth fixes

build-pinebookpro.sh
The Pinebook Pro daily builds have been failing for a while. Looks like we're running out of space on the GitHub actions runner.
This should free up plenty of space to allow these builds to start working again.
=> pinebookpro: Clean up some transient files to save space

etc/config/hooks/live/001-install-flatpaks.chroot
Like how we used to for Epiphany, but only allowing `org.freedesktop.*` runtimes/extensions. Also ensures we use `--system` with each command to be explicit about the intent.
I named the remote `freedesktop` since that's what it's filtered down to. I'm not sure if we want to do that or just call it `flathub`, but I kind of like naming it what it's filtered to.
=> Add filtered Flathub for FreeDesktop extensions

etc/config/hooks/live/001-install-flatpaks.chroot
Depends on https://github.com/elementary/tasks/runs/2586598768 passing and Tasks being installable from the Flatpak repo
=> Hooks: Install Tasks as Flatpak

etc/config/hooks/live/001-install-flatpaks.chroot
Depends on https://github.com/elementary/mail/runs/2586738375 passing and Mail being installable from the Flatpak repo.
=> Hooks: Install Mail as Flatpak

etc/config/hooks/live/001-install-flatpaks.chroot
It's failing to install in current daily builds because we have to choose between `master` and `stable`
=> Flatpak: specify `master` branch of Calculator

etc/config/hooks/live/001-install-flatpaks.chroot
In case we start building any more of them into a `stable` branch, this will prevent #497 from happening again.
=> Flatpak: Specify `master` for all missing branches

etc/config/hooks/live/001-install-flatpaks.chroot
Fixes #506. Epiphany and Evince omitted for now because we don't have them available in a stable branch. See https://github.com/elementary/browser/issues/34 and https://github.com/elementary/evince/issues/13.
=> Flatpak: point first-party apps to stable

etc/config/hooks/live/001-install-flatpaks.chroot
Need to make sure this passes first https://github.com/elementary/browser/runs/3226972932 (and Epiphany is in the AppCenter remote)
=> Flatpak: include Epiphany from stable

build.sh, live-build-fix-shim-remove.patch
Fixes #514 
I've tested that this is enough to get the RC image building locally.
The `shim-signed` package from Ubuntu was updated 2 days ago to include some flags in the debian control file to prevent accidental removal of the package. During the phase of the build that was failing, live-build temporarily installs grub and the shim to make the boot sector of the iso image, and then tries to remove them again afterwards to clean up after itself. Since Ubuntu updated `shim-signed`, it wasn't able to remove it anymore, without an additional flag.
I'll get this proposed as a patch upstream and then we can add a comment in here with a link to the PR. But I've proposed here first so we can at least get going with building an RC image.
=> Allow live-build to remove protected pkgs in iso bootloader stage

build.sh
Patch has been approved upstream, just waiting on CI:
https://salsa.debian.org/live-team/live-build/-/merge_requests/255
Leave a note for ourselves in the future that we can remove this once there's a stable release incorporating the fix.
=> Leave comment about live-build shim fix

etc/auto/config
Probably worth waiting until after we've got an RC image to merge this in case it breaks it again :sweat_smile: 
I remember putting this in place to solve some build failures I was seeing in GitHub Actions that I wasn't getting locally, probably due to my geographic location vs. where the GitHub builder was and which mirrors it was choosing.
It significantly slows down the build, but there was never any real science behind the numbers I chose. So lets try something less (but still more than the defaults), and see if we gain some speed without getting random failures again.
=> Experiment with some faster timeouts on the apt mirrors

.github/workflows/daily-6.0.yml, .github/workflows/stable.yml
I think this is why it's failing, due to the Bullseye release
=> Actions: set container to Buster

etc/config/hooks/live/001-install-flatpaks.chroot
Does the same as `-y` and also reduces the "pretty" output that ends up clogging up logs. For prior art, see e.g.: https://github.com/elementary/capnet-assist/blob/4417b38e16cff8bbc948bd0d44ea1fb694d6bf14/debian/postinst#L6
=> Flatpak: Use `--noninteractive` flag

etc/config/hooks/live/001-install-flatpaks.chroot
This should solve page crashes in the live environment with Epiphany now that we're shipping 41
I've confirmed that this fixes Ephy crashes in a fresh install of OS 6 daily
=> Bump FD.o GL to 21.08

etc/terraform-stable-azure.conf
Unless we want to keep this always, we can drop it again.
=> Stable config: remove `-rc` suffix

.github/workflows/daily-6.1-arm.yml, build-pinebookpro.sh, build-rpi.sh
Also bumps the ARM versions to 6.1 for accuracy. We'll want to bump these to 7.0 once someone can test and validate them but in the meantime they should reflect the same version the OS itself says.
=> Workflows: Rename ARM workflow for clarity

etc/config/package-lists.default/pool.list.binary
This doesn't exist in `jammy` anymore and is causing the daily builds to fail as a result. There's not a lot of information about it online but it's something to do with being able to install with the iso mounted as a loop filesystem. Ubuntu have dropped it, and I highly doubt it's compatible with our installer anyway :shrug:
=> Remove lupin-support from pool

README.md
Depending on the system setting of the host the  Elementary logo will display as black when in light mode and white when in dark mode as per Github documentation.
=> Add responsive light/dark mode logos to README.md

etc/config/bootloaders/grub-pc/grub.cfg, etc/config/bootloaders/isolinux/live.cfg.in
Adds an option to the live CD boot menu to boot with `nomodeset` enabled, which should allow the ISO to boot on hardware we don't have working graphics drivers for.
Ubuntu upstream does something similar:
https://askubuntu.com/questions/1138137/what-is-safe-graphics-mode
=> Add safe graphics option to boot menu

etc/auto/config
Related to #252 
According to https://manpages.ubuntu.com/manpages/bionic/man1/lb_config.1.html we have to explicitly enable security repositories.
> --security true|false
>            defines  if  the security repositories specified in the security mirror options should
>            be used or not.
=> Enable security repositories

etc/auto/config
Related to #252 
I had to dig through the code of `live-build` to find out that the versions of Debian and Ubuntu are implemented differently. By using `debian:latest` to build our images, the `mode` `ubuntu` is not supported. Only security repositories are enabled for `mode` `debian`: https://salsa.debian.org/live-team/live-build/-/blob/master/functions/sourcelist.sh#L77
```
deb mirror://mirrors.ubuntu.com/mirrors.txt jammy main restricted universe multiverse
deb-src mirror://mirrors.ubuntu.com/mirrors.txt jammy main restricted universe multiverse
deb mirror://mirrors.ubuntu.com/mirrors.txt jammy-updates main restricted universe multiverse
deb-src mirror://mirrors.ubuntu.com/mirrors.txt jammy-updates main restricted universe multiverse
```
```
deb mirror://mirrors.ubuntu.com/mirrors.txt …
```
=> Switch mode to debian

.github/workflows/daily-6.1-arm.yml
It looks like currently Pinebook builds are failing which is causing Raspberry Pi builds to be canceled
=> ARM: don't fail whole workflow if one config fails

.github/workflows/daily-6.1-arm.yml, README.md
The issue with failing Pinebook Pro builds occured around 6 months ago. We use the WiFi and Bluetooth firmware from Manjaro. [6 months ago a file we rely on was renamed](https://gitlab.manjaro.org/manjaro-arm/packages/community/ap6256-firmware/-/commit/056d5f6776e515f90bbbbead1be06857aaef17d0). Because of this our Pinebook Pro builds started to fail:
```
...
Running in chroot, ignoring request.
* Stopping SMP IRQ Balancer: irqbalance
...done.
Processing triggers for man-db (2.9.1-1) ...
Cloning into 'ap6256-firmware'...
cp: cannot stat 'nvram_ap6256.txt': No such file or directory
...
```
[Daily Build (ARM) · elementary/os@73d4076](https://github.com/elementary/os/actions/runs/3208455433/jobs/5244325444#step:4:12865)
@tintou fixed the issue in [pinebookpro: Update to latest …
=> Fix Pinebook Pro builds

etc/config/archives/elementary.list, etc/config/archives/patches.list
The PPAs are available via HTTPS since february as per https://blog.launchpad.net/ppa/new-domain-names-for-ppas
=> archives: Use https link for the PPAs

build-rpi.sh
This is a minor fix for the Raspberry Pi build script, where the loop device name was overly-constrained in a regular expression.
```
loop9p1 - matched
loop10p1 - not a match
```
I changed the regular expression slightly so that more than one digit in the loop device name would be accepted.
```diff
- .*(loop[0-9])p.*
+ .*(loop[0-9]+)p.*
```
```
loop9p1 - matched
loop10p1 - matched
```
On host systems with more than 10 loop devices already present, the existing regular expression wouldn't match the newly-created loop device. The failed match resulted in the entire `kpartx` command output ending-up in the `device` variable, causing mkfs commands to fail. Here's an example mkfs command in a failed build:
```
mkfs.vfat -n system-boot '/dev/mapper/add map loop31p1 (253:0): 0 500000 linear 7:31 …
```
=> RPi Build Script: Fix loopback device setup on system with >10 devices

README.md, build-rpi.sh
I was pleasantly surprised at how straightforward it was to make these changes and build the image locally--your documentation is superb.
The build script (I used a 22.04 base image) had no trouble producing the image, and the image itself set up and installed just fine on my Raspberry Pi.
In fact, I'm opening this PR _from_ the Pi itself.
I'm not going to lie and claim that it isn't _painfully_ slow to use, but my wifi and peripherals are all recognized out of the box, and I'm running a 1440p display, so I'm not complaining.
=> Update RPi build script to Horus

314-follow-symlinks-when-measuring-size-of-efi-files.patch, build.sh
Fixes #657 
Ubuntu made a change to their GRUB/EFI packages to start symlinking some stuff which broke the size calculations in `live-build`. I've submitted a patch upstream, but we can include it here to get our builds working again in the mean time
=> Fix 7.0 builds

etc/auto/config
Partially reverts #328 
I'm seeing regular issues with these mirror lists on my installed system where `apt` will get stuck on some garbage tier mirror while trying to do updates.
Ever since #328 has been merged, we've been seeing the daily builds of the iso fail due to the same issue on occasion, and it feels like the frequency of this is increasing.
It also seems I'm not alone in this issue: 
- #636 
- https://github.com/orgs/elementary/discussions/271
I think we did this originally due to something about maybe ending up with a country specific mirror (i.e. `us.archive.ubuntu.com`) after installation, or maybe the fact that the default mirror without a country prefix only has servers in the UK and US and is therefore maybe less efficient for users elsewhere in the world.
Either way, I …
=> Stop using mirror lists

etc/config/package-lists/pool.list.binary
This allows the "additional drivers" step of the installer to install these drivers for VMware support without an internet connection.
Should improve our VM support somewhat.
Related to https://github.com/elementary/installer/issues/723
=> Add open-vm-tools to pool

.github/workflows/daily-arm.yml, .gitignore, README.md, build-pinebookpro.sh, build-rpi.sh
Fix #727
Closes #728
The fix for https://bugs.launchpad.net/ubuntu/+source/base-files/+bug/2054925 does not seem to be released for Ubuntu 20.04 LTS. This issue didn't occur when I tested on OS 8 RC, so switch build environment to Ubuntu 24.04 LTS.
- Update build environment to Ubuntu 24.04 LTS
- Do not install `python3-distutils` that is no longer provided since Ubuntu 24.04 LTS
- Install pip3 and boto3 from apt
=> arm64: Build on Noble

README.md
The previous badge points to the old workflow removed in #725.
=> README: Update stable badge

build.sh
Fixes #723 
`apt-key` will be removed in the upcoming Debian Trixie release. This PR ensures compatibility with newer build environments, which is useful for https://github.com/elementary/os/pull/754.
=> Replace deprecated `apt-key`

.github/workflows/daily-8.0-arm64.yml, build-arm64.sh, etc/auto/config, etc/config/package-lists/pool.list.binary, etc/terraform-arm64.conf, etc/terraform-daily-8.0-azure-arm64.conf, workflows-arm64.sh
This PR introduces native ARM64 build support. Related to #682.
Thanks to @t3rminus for the initial attempt.
1. A newer version of `live-build` is required.
2. ~The `io.elementary.installer` package is currently not included in [metapackages/live-arm64](https://github.com/elementary/metapackages/blob/noble/live-arm64), preventing installation to disk.~
Tested using [UTM](https://github.com/utmapp/UTM) on Apple Silicon Mac.
=> ARM: native build support
