- .github/workflows/distinst-weekly.yml
Build and upload a Installer/distinst based .iso every Wednesday night.
> Add weekly distinst workflow

- etc/terraform-daily-6.0-azure.conf
__CHANGES:__
* update codename to focal instead of eoan.
* Default to distinst installer instead of ubiquity.
> Update Codename in 6.0 dailies

- etc/config/package-lists.distinst/desktop.list.chroot_install
This should be part of the metpackages now that it's added into `seeds`
> Remove hardcoded initial setup

- etc/terraform.conf
> use default for PACKAGE_LISTS_SUFFIX

- upload.sh
__CHANGES:__
* create and upload a `.torrent` file for stable iso builds
> create and upload a torrentfile when stable isos are generated

- upload.py
Reduced a few lines of code using list comprehension to initialize the variables: `KEY`, `SECRET`, `ENDPOINT`, `BUCKET`, `FILEPATH`, `FILENAME`.
> refactor: Changes in method initialization of variables

- .github/workflows/daily-5.1.yml
- .github/workflows/daily-6.0-pinebookpro.yml
- .github/workflows/daily-6.0.yml
- .github/workflows/distinst-weekly.yml
- .github/workflows/stable.yml
- formatting
- add pinebook build on master push
- allow manually triggering builds
> Update GitHub actions

- .github/workflows/daily-5.1.yml
- .github/workflows/daily-6.0-pinebookpro.yml
- .github/workflows/daily-6.0.yml
- .github/workflows/distinst-weekly.yml
- .github/workflows/stable.yml
> Revert "Update GitHub actions"

- etc/config/hooks/live/001-install-flatpaks.chroot
> Revert: 'Ensure permissions are sensible'

- etc/terraform-daily-6.0-azure.conf
To go with https://github.com/elementary/os-patches/pull/146
> Update 6.0 image codename

- build-pinebookpro.sh
Should be no functional changes here, just fixing the code style
> pinebookpro: Fix shellcheck warnings for build script

- etc/config/hooks/live/001-install-flatpaks.chroot
> Add elementary system Flatpak repo

- etc/config/hooks/live/001-install-flatpaks.chroot
> Install calculator from Flatpak

- etc/config/hooks/live/001-install-flatpaks.chroot
I confirmed Evince is available in our repo and installed it and it works fine :)
> Install Evince from flatpak

- etc/config/hooks/live/001-install-flatpaks.chroot
as far as I can tell everything works as expected, even clipboard stuff
> Install screenshot from flatpak

- etc/config/hooks/live/001-install-flatpaks.chroot
Thanks to https://github.com/elementary/camera/pull/161
> Install Camera as Flatpak

- etc/config/hooks/live/001-install-flatpaks.chroot
Move apps to their own lines, improve file comment
> Flatpak: improve formatting

- etc/config/hooks/live/001-install-flatpaks.chroot
> Flatpaks: specify daily branch for Camera

- etc/config/hooks/live/001-install-flatpaks.chroot
> Flatpaks: specify daily branch for Epiphany

- etc/config/hooks/live/001-install-flatpaks.chroot
> Flatpak: Install `org.freedesktop.Platform.GL.default`

- etc/config/hooks/live/001-install-flatpaks.chroot
> Flatpak: Assume yes for GL installation

- etc/config/hooks/live/001-install-flatpaks.chroot
We're having issues with secrets in the sandbox, so the fastest way to deal with it is to ship the deb for now
> Flatpak: Remove mail

- etc/terraform-stable-azure.conf
> Config: Build Odin release candidate

- etc/terraform.conf
Same changes as in #510 minus the RC suffix. Just makes it more straightforward for local builds.
> Terraform: Update default configuration for Odin

- etc/terraform-stable-azure.conf
Merge once we're ready to spin a release ISO, before making a stable release.
> Terraform: remove -rc suffix

- etc/config/hooks/live/001-install-flatpaks.chroot
Waiting on https://github.com/elementary/seeds/pull/83 to make sure we pull in Deb tasks
> Flatpak: remove Tasks

- build-pinebookpro.sh
- build-rpi.sh
- build.sh
> Also output checksums to build log

- README.md
This is just a super small change to make the readme's badges reflect current ci changes.
> update readme with new ci badges and smaller icon

- etc/config/hooks/live/001-install-flatpaks.chroot
> Install elementary apps via apt

- etc/config/bootloaders/grub-pc/grub.cfg
- etc/terraform.conf
> Update terraform.config to 7.0

- .github/workflows/daily-arm.yml
Should fix our ARM build failures due to lack of space
> Free more space for ARM builds

- README.md
- Remove temporary containers after use
- Allow TTY to be interactive so you can interrupt the build
> README: cleanup docker commands

- .github/workflows/stable.yml
We kick off monthly updates so why not build a new ISO every month?
> Build stable once a month

- .github/workflows/stable-8.0
- etc/terraform-stable-8.0-azure.conf
> Build Stable 8.0

- build-rpi.sh
> Raspberry Pi: bump to noble

- etc/config/hooks/live/apparmor-profiles.chroot
> Revert "Create apparmor-profiles.chroot"

- .github/ISSUE_TEMPLATE/build_system.yml
Similar to elementary/.github#39
> build_system: Add OS Architecture

- .github/workflows/daily-8.0.yml
- README.md
afaik this should all be pretty self contained right?
> master → main
